#!/usr/bin/env bash

CURL_OPTION="-v"

set -e
exec 3>&1
exec 1>&2
#set -x

payload=$(mktemp /tmp/resource-in.XXXXXX)
cat > "${payload}" <&0

echo "Using temporary directory ${payload}"

format="markdown"
color="$(jq -r '.params.color // "00EA43"' < "${payload}")"

text_file="$(jq -r '.params.text_file // ""' < "${payload}")"
text=$(jq -r '(.params.attachments // null)' < $payload)

FILE_CONTENT=""
[[ -n "${text_file}" && -f "${text_file}" ]] && FILE_CONTENT="$(cat "${text_file}")"
if [[ "${text}" == "null" && -n $FILE_CONTENT ]]; then
  text=$FILE_CONTENT
fi

#text=$(echo "$text" | envsubst)

webhook_url="$(jq -r '.source.url' < "${payload}")"
redacted_webhook_url=$(echo "${webhook_url}" | sed -e 's#/\([^/\.]\{2\}\)[^/.]\{5,\}\([^/.]\{2\}\)#/\1…\2#g' | jq -R .)

url_path="$(echo ${webhook_url} | sed -e "s/https\{0,1\}:\/\/[^\/]*\(\/[^?&#]*\).*/\1/")"
curl ${CURL_OPTION} -d "${text}" "${webhook_url}" 2>&1 | sed -e "s#${url_path}#***WEBHOOK URL REDACTED***#g"

timestamp=$(date +%s)
metadata="$(cat <<EOF
{
  "version": {"timestamp": "${timestamp}"},
  "metadata": [
    {"name": "url", "value": ${redacted_webhook_url}},
    {"name": "BUILD_PIPELINE_NAME", "value": "${BUILD_PIPELINE_NAME}"}
  ]
}
EOF
)"

echo "$metadata"  >&3
